### ISSUE TITLE
Keep it up

### ISSUE THREAD

**Issue by zhigui** [zhiquan-yu/meditor#9]
无意间又再次看到了这个项目，记得上次是去年的8月份吧。
很高兴看到你后续还能继续更新和维护这个这个编辑器，而不仅仅是一道题！
很棒， keep it up!  👍

**Comment by naicha-gg** [comment]
@zhigui 哈，你是面试我的吗？我现在在小红书工作，专门开发各种编辑器，真是缘分哎！

**Comment by zhigui** [comment]
😁   恭喜你入了编辑器的坑！

**Comment by zhigui** [comment]
@zhiquan-yu  恭喜你入了编辑器的坑！ 😁
